apiVersion: v1
kind: Service
metadata:
  name: {{ include "multus-attacher.fullname" . }}
  labels:
    {{- include "multus-attacher.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
      name: health
    - port: {{ .Values.service.webhookPort }}
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    {{- include "multus-attacher.selectorLabels" . | nindent 4 }}
